sudo: required

language: python
python:
  -  "3.6"

services:
  - docker

script: true

after_success:
- bash <(curl -s https://raw.githubusercontent.com/sesam-community/guidelines/BaardBouvet-patch-1/after_success.sh)